project_id = "btqccksigmohyjdxgrrj"

[functions.voice-websocket]
verify_jwt = false

[functions.serve-audio-snippet]
verify_jwt = false

[functions.business-intelligence]
verify_jwt = false

[functions.test-voice-call]
verify_jwt = true
