project_id = "btqccksigmohyjdxgrrj"

[functions.voice-websocket]
verify_jwt = false

[functions.chat-websocket]
verify_jwt = false

[functions.serve-audio-snippet]
verify_jwt = false

[functions.business-intelligence]
verify_jwt = false

[functions.test-voice-call]
verify_jwt = true

[functions.sms-handler]
verify_jwt = false

[functions.agent-transfer]
verify_jwt = false

[functions.analyze-website]
verify_jwt = false
